language: cpp
dist: bionic
addons:
  apt:
    sources:
      - ppa:ubuntu-toolchain-r/test
    packages:
      - build-essential
      - gcc-8
      - g++-8
      - freeglut3-dev
      - libxi-dev
      - libxmu-dev
      - liblapack-dev
      - libqt5widgets5
      - qt5-default
      - cmake
install:
  - export CC="gcc-8"
  - export CXX="g++-8"
before_script:
  # setup OpenSceneGraph
  - wget https://sourceforge.net/projects/dependencies/files/OpenSceneGraph/OpenSceneGraph-3.4-ubuntu-18.04.tar.xz
  - tar -xf OpenSceneGraph-3.4-ubuntu-18.04.tar.xz
  - export OSG_DIR=$(pwd)/OpenSceneGraph-3.4
  - export LD_LIBRARY_PATH=$OSG_DIR/lib64:$LD_LIBRARY_PATH
  - export LD_LIBRARY_PATH=$OSG_DIR/lib64/osgPlugins-3.4.2:$LD_LIBRARY_PATH
  - export PATH=$OSG_DIR/bin:$PATH
  - export PKG_CONFIG_PATH=$OSG_DIR/lib64/pkgconfig:$PKG_CONFIG_PATH
  # setup OpenSim v3.3
  - wget https://sourceforge.net/projects/dependencies/files/opensim-core/opensim-core-3.3-ubuntu-18.04.tar.xz
  - tar -xf opensim-core-3.3-ubuntu-18.04.tar.xz
  - export OPENSIM_HOME=$(pwd)/opensim-core
  - export PATH=$OPENSIM_HOME/bin:$PATH
  - export LD_LIBRARY_PATH=$OPENSIM_HOME/lib:$LD_LIBRARY_PATH
script:
  # build SCONE
  - git submodule update --init
  - ls -la $OSG_DIR/lib64
  - mkdir build
  - cd build
  - cmake ../
      -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_INSTALL_PREFIX=../install
      -DOPENSIM_INSTALL_DIR=$OPENSIM_HOME
      -DOSG_DIR=$OSG_DIR
      -DOSG_INCLUDE_DIR=$OSG_DIR/include
      -DOSG_LIBRARY_RELEASE=$OSG_DIR/lib64/libosg.so
      -DOSGQT_LIBRARY_RELEASE=$OSG_DIR/lib64/libosgQt.so
      -DOSGVIEWER_LIBRARY_RELEASE=$OSG_DIR/lib64/libosgViewer.so
      -DOSGUTIL_LIBRARY_RELEASE=$OSG_DIR/lib64/libosgUtil.so
      -DOSGDB_LIBRARY_RELEASE=$OSG_DIR/lib64/libosgDB.so
      -DOSGSHADOW_LIBRARY_RELEASE=$OSG_DIR/lib64/libosgShadow.so
      -DOPENTHREADS_LIBRARY_RELEASE=$OSG_DIR/lib64/libOpenThreads.so
  - make -j8