language: cpp
sudo: false
dist: bionic
addons:
  apt:
    sources:
      - ppa:chris-lea/redis-server
    packages:
      - cmake
      - build-essential
      - gcc
      - g++
      - freeglut3-dev
      - libxi-dev
      - libxmu-dev
      - liblapack-dev
      - libqt5widgets5
before_install:
  # setup OpenSceneGraph
  - wget https://sourceforge.net/projects/dependencies/files/OpenSceneGraph/OpenSceneGraph-3.4-ubuntu-18.04.tar.xz
  - tar -xvf OpenSceneGraph-3.4-ubuntu-18.04.tar.xz $HOME/OpenSceneGraph-3.4
  - export OSG_DIR=$HOME
  - export LD_LIBRARY_PATH=$OSG_DIR/lib64:$LD_LIBRARY_PATH
  - export LD_LIBRARY_PATH=$OSG_DIR/lib64/osgPlugins-3.4.2:$LD_LIBRARY_PATH
  - export PATH=$OSG_DIR/bin:$PATH
  - export PKG_CONFIG_PATH=$OSG_DIR/lib64/pkgconfig:$PKG_CONFIG_PATH
  # setup OpenSim v3.3
  - wget https://sourceforge.net/projects/dependencies/files/opensim-core/opensim-core-3.3-ubuntu-18.04.tar.xz
  - tar -xvf opensim-core-3.3-ubuntu-18.04.tar.xz $HOME
  - export OPENSIM_HOME=$HOME/opensim-core
  - export PATH=$OPENSIM_HOME/bin:$PATH
  - export LD_LIBRARY_PATH=$OPENSIM_HOME/lib:$LD_LIBRARY_PATH
install:
  # build SCONE
  - git submodule update --init
  - mkdir build
  - cd build
  - cmake ../
      -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_INSTALL_PREFIX=../install
      -DOSG_DIR=$OSG_DIR
      -DOSG_INCLUDE_DIR=$OSG_DIR/include
      -DOPENSIM_INSTALL_DIR=$OPENSIM_HOME
  - make